const {python}=require('./browser_support.cjs');
/* Synthetic transactions only; isolated server and browser profile. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),run=path.join(root,'.local-data','continuous-review-qa-'+Date.now());
fs.mkdirSync(run,{recursive:true});const connFile=path.join(run,'connection.json');
const wait=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,page;
(async()=>{
  server=spawn(python,['-B','-X','utf8',path.join(root,'backend','run_app.py'),'--data-dir',path.join(run,'workspace'),'--no-ocr','--connection-file',connFile],{cwd:root,windowsHide:true,stdio:'ignore'});
  for(let i=0;i<100&&!fs.existsSync(connFile);i++)await wait(100);
  const conn=JSON.parse(fs.readFileSync(connFile,'utf8'));
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1360,height:980}});
  await context.addInitScript(()=>localStorage.setItem('flowlens-guide-v1',JSON.stringify({skipped:true})));
  page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(conn.url);await page.locator('#create-book').click();await page.locator('#book-name').fill('连续核验合成账本');await page.locator('#name-form [type="submit"]').click();
  await page.waitForFunction(()=>!document.querySelector('#choose-files').disabled);
  await page.locator('#file-input').setInputFiles({name:'三个疑点.csv',mimeType:'text/csv',buffer:Buffer.from('交易日期,金额,收支,币种,交易对方\n2026-01-01,xx,支出,CNY,店甲\n2026-01-02,xx,收入,CNY,店乙\n2026-01-03,xx,支出,CNY,店丙\n')});
  await page.locator('#kpi-pending').filter({hasText:'3'}).waitFor();await page.locator('#review-shortcut').click();
  await page.locator('[data-review-record]').first().click();await page.locator('#detail-dialog').waitFor();
  assert.deepEqual(await page.locator('.raw-attention').evaluateAll(rows=>rows.map(r=>r.dataset.rawIndex)),['1']);
  assert.deepEqual(await page.locator('.field-attention [name]').evaluateAll(inputs=>inputs.map(i=>i.name)),['amount']);
  await page.locator('[name="amount"]').fill('999');await page.locator('#detail-dialog [data-close]').click();
  await page.locator('[data-review-record]').nth(1).click();await page.locator('#detail-dialog').waitFor();
  assert.equal(await page.locator('[name="counterparty"]').inputValue(),'店乙');
  assert.equal(await page.locator('[name="amount"]').inputValue(),'');
  await page.locator('[name="amount"]').fill('invalid');await page.locator('#save-record').click();
  await page.locator('#detail-error').waitFor();assert.equal(await page.locator('[name="counterparty"]').inputValue(),'店乙');
  assert.equal(await page.locator('#nav-pending').innerText(),'3');
  await page.evaluate(()=>{window.detailCloses=0;document.querySelector('#detail-dialog').addEventListener('close',()=>window.detailCloses++);});
  await page.locator('[name="amount"]').fill('20');await page.locator('#save-record').click();
  await page.waitForFunction(()=>document.querySelector('[name="counterparty"]')?.value==='店丙');
  assert.equal(await page.evaluate(()=>window.detailCloses),0);
  assert.equal(await page.locator('#record-note').inputValue(),'');
  assert((await page.locator('#sequence-position').innerText()).includes('剩余 2 条'));
  await page.screenshot({path:path.join(run,'continuous-review.png')});
  await page.locator('[name="amount"]').fill('30');await page.locator('#auto-next').uncheck();await page.locator('#save-record').click();
  await page.locator('#detail-dialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('#nav-pending').innerText(),'1');
  await page.locator('[data-review-record]').click();await page.locator('#detail-dialog').waitFor();
  assert.equal(await page.locator('[name="counterparty"]').inputValue(),'店甲');
  assert.equal(await page.locator('[name="amount"]').inputValue(),'');
  await page.locator('[name="amount"]').fill('10');
  let release,received;const held=new Promise(r=>release=r),arrived=new Promise(r=>received=r);
  await page.route('**/api/action',async route=>{const response=await route.fetch();received();await held;await route.fulfill({response});});
  await page.locator('#save-record').click();await arrived;
  await page.keyboard.press('Escape');release();
  await page.locator('#nav-pending').filter({hasText:'0'}).waitFor();
  assert.equal(await page.locator('#detail-dialog').isVisible(),false);
  await page.locator('#history').click();assert.equal(await page.locator('.history-event').count(),3);
  await page.locator('#history-dialog [data-close]').click();await page.locator('[data-page="records"]').click();
  await page.locator('[data-record]').first().click();await page.locator('#detail-dialog').waitFor();
  assert.equal(await page.locator('.raw-attention, .field-attention').count(),0);
  assert.equal(await page.locator('#attention-legend').isVisible(),false);
  assert.equal(errors.length,0,errors.join('\n'));
  const results=['异常金额同时高亮原列与编辑字段','中途退出不保存未提交输入','无效输入停留当前条且不跳过','从中间记录按队列继续，弹窗不关闭','每条备注清空且可留空','关闭自动继续后保存退出','保存进行中 Esc 退出后不会重新弹出','三条实际保存与历史数量一致','已确认记录重开后不再保留旧高亮'];
  fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({results,errors},null,2));console.log(JSON.stringify({run,results,errors},null,2));
})().catch(async e=>{console.error(e);if(page)await page.screenshot({path:path.join(run,'failure.png')}).catch(()=>{});console.error(run);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server&&server.exitCode===null)server.kill();});
