/* Isolated headless browser: no personal browser profile or old ledger used. */
const fs = require('node:fs');
const path = require('node:path');
const {spawn,spawnSync} = require('node:child_process');
const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname,'..');
const run = path.join(root,'.local-data','browser-qa-'+Date.now());
fs.mkdirSync(run,{recursive:true});
const connection = path.join(run,'connection.json');
const {python}=require('./browser_support.cjs');
const script = path.join(root,'backend','run_app.py');
const wait = ms=>new Promise(r=>setTimeout(r,ms));
let server, browser, testPage;
async function start() {
  if(fs.existsSync(connection)) fs.unlinkSync(connection);
  server=spawn(python,['-B','-X','utf8',script,'--data-dir',path.join(run,'workspace'),'--no-ocr','--connection-file',connection],{cwd:root,windowsHide:true,stdio:'ignore'});
  for(let i=0;i<100 && !fs.existsSync(connection);i++) await wait(100);
  return JSON.parse(fs.readFileSync(connection,'utf8'));
}
async function stop() {if(server && server.exitCode===null){const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped;}}
const results=[];
(async()=>{
  let conn=await start();
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
  const page=await context.newPage();
  testPage=page;
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto(conn.url);
  await page.locator('#guide-dialog').waitFor();
  await page.screenshot({path:path.join(run,'guide-create.png')});
  await page.locator('#guide-next').click();
  await page.getByLabel('账本名称',{exact:true}).fill('合成验收账本');
  await page.locator('#name-form').getByRole('button',{name:'保存',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#choose-files').disabled);
  await page.locator('#guide-dialog').waitFor();
  await page.locator('#guide-next').click();
  await page.locator('#file-input').setInputFiles({name:'读取核验.csv',mimeType:'text/csv',buffer:Buffer.from('交易日期,金额,收支,币种,交易对方,摘要\n2026-09-01,12.30,支出,人民币,合成商店,午餐\n2026-09-02,xx,收入,人民币,合成退款,核验示例\n2026-09-03,3,支出,人民币,<img src=x onerror=alert(1)>,文本安全测试\n')});
  await page.locator('#kpi-total').filter({hasText:'3'}).waitFor();
  assert.equal(await page.locator('#kpi-pending').innerText(),'1');
  await page.locator('#guide-dialog').waitFor();
  await page.screenshot({path:path.join(run,'guide-review.png')});
  await page.locator('#guide-next').click();
  await page.locator('#page-review').waitFor();
  await page.locator('[data-page="overview"]').click();
  await page.locator('#show-guide').click();
  await page.keyboard.press('Escape');
  await page.reload();
  await page.locator('#kpi-total').filter({hasText:'3'}).waitFor();
  assert.equal(await page.locator('#guide-dialog').isVisible(),false);
  // Later server restarts use fresh ports; keep unrelated regression cases guide-free.
  await context.addInitScript(()=>localStorage.setItem('flowlens-guide-v1',JSON.stringify({skipped:true})));
  results.push('三步遮罩指引可操作、可重开，Esc 跳过后刷新不重复弹出');
  assert.equal(await page.locator('#sources').getByRole('img').count(),0);
  results.push('导入三条、待核验一条，未知金额不填零');
  await page.screenshot({path:path.join(run,'overview-partial.png'),fullPage:true});
  await page.getByRole('button',{name:'导出有效流水',exact:true}).click();
  assert(await page.locator('#download-full').isDisabled());
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#download-partial').click();
  const download=await downloadPromise;await download.saveAs(path.join(run,'partial.json'));
  assert.equal(JSON.parse(fs.readFileSync(path.join(run,'partial.json'),'utf8')).partial,true);
  results.push('部分导出明确选择，实际下载落盘且 partial=true');
  await page.locator('#review-shortcut').click();
  await page.getByRole('button',{name:'对照并核验',exact:true}).click();
  await page.locator('[name="amount"]').fill('20.00');
  assert.equal(await page.locator('#record-note').getAttribute('required'),null);
  await page.locator('#save-record').click();
  await page.locator('#detail-dialog').waitFor({state:'hidden'});
  await page.getByText('本批次没有待处理的读取问题。',{exact:false}).waitFor();
  await page.getByRole('button',{name:'修改历史与撤销',exact:true}).click();
  assert((await page.locator('#history-content').innerText()).includes('未填写备注'));
  await page.locator('#undo').click();
  await page.getByRole('button',{name:'对照并核验',exact:true}).waitFor();
  results.push('卡片进入核验，不填理由修正保存、有历史、可撤销恢复待核验');
  await page.getByRole('button',{name:'对照并核验',exact:true}).click();
  await page.locator('[name="amount"]').fill('20');
  await page.locator('#record-note').fill('再次核实合成来源');
  await page.locator('#save-record').click();
  await page.locator('#detail-dialog').waitFor({state:'hidden'});
  await page.locator('[data-page="overview"]').click();
  await page.locator('#file-input').setInputFiles({name:'追加.csv',mimeType:'text/csv',buffer:Buffer.from('交易日期,金额,收支,币种\n2026-09-04,8,支出,人民币\n')});
  await page.locator('#kpi-total').filter({hasText:'4'}).waitFor();
  await page.locator('[data-page="records"]').click();
  await page.getByText('共 4 条',{exact:false}).waitFor();
  assert.equal(await page.locator('#records-body img').count(),0);
  results.push('追加后整本四条，来源文本安全呈现');
  await page.screenshot({path:path.join(run,'records.png'),fullPage:true});
  await stop();conn=await start();
  await page.goto(conn.url);
  await page.locator('#kpi-total').filter({hasText:'4'}).waitFor();
  assert.equal(await page.locator('#kpi-pending').innerText(),'0');
  results.push('重启恢复四条、两批和已核验状态');
  await page.getByRole('button',{name:'导出有效流水',exact:true}).click();
  const fullPromise=page.waitForEvent('download');await page.locator('#download-full').click();
  const full=await fullPromise;await full.saveAs(path.join(run,'complete.json'));
  const exported=JSON.parse(fs.readFileSync(path.join(run,'complete.json'),'utf8'));
  assert.equal(exported.records.length,4);assert.equal(exported.partial,false);
  results.push('完整导出实际落盘，四条有效记录与页面一致');
  await page.getByRole('button',{name:'＋ 新建',exact:true}).click();
  await page.getByLabel('账本名称',{exact:true}).fill('隔离账本');
  await page.locator('#name-form').getByRole('button',{name:'保存',exact:true}).click();
  await page.locator('#kpi-total').filter({hasText:'0'}).waitFor();
  await page.locator('#book-select').selectOption({label:'合成验收账本'});
  await page.locator('#kpi-total').filter({hasText:'4'}).waitFor();
  results.push('新建第二账本并切回，记录与修订隔离');
  await page.screenshot({path:path.join(run,'overview-complete.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1),'Mobile page must not overflow horizontally');
  await page.screenshot({path:path.join(run,'mobile.png'),fullPage:true});
  results.push('390px 窄窗口无全页横向溢出');
  await page.setViewportSize({width:1440,height:1050});
  await page.locator('[data-page="records"]').click();
  await page.locator('[data-record]').first().click();
  await page.locator('[name="amount"]').fill('9');
  await page.locator('#record-note').fill('过期页面不应覆盖新修订');
  const second=await context.newPage();await second.goto(conn.url);
  await second.waitForFunction(()=>!document.querySelector('#choose-files').disabled);
  await second.locator('[data-page="records"]').click();
  await second.locator('[data-record]').first().click();
  await second.locator('[name="amount"]').fill('8.50');
  await second.locator('#record-note').fill('另一个页面核对后修正');
  await second.locator('#save-record').click();
  await second.locator('#detail-dialog').waitFor({state:'hidden'});
  await page.locator('#save-record').click();
  await page.locator('#detail-error').filter({hasText:'数据已被其他操作更新'}).waitFor();
  results.push('双页面过期修改被拒绝，保留用户未保存输入');
  await second.close();
  await stop();
  const seed=spawnSync(python,['-B','-X','utf8',path.join(root,'scripts','seed_page_fixture.py'),path.join(run,'workspace')],{cwd:root,windowsHide:true,encoding:'utf8'});
  assert.equal(seed.status,0,seed.stderr);
  conn=await start();await page.goto(conn.url);
  await page.locator('#kpi-pages').filter({hasText:'1'}).waitFor();
  assert.equal(await page.locator('#kpi-total').innerText(),'0');
  await page.locator('[data-page="review"]').click();
  await page.getByRole('button',{name:'查看原页 / 核对笔数',exact:true}).click();
  assert.equal(await page.locator('#page-evidence img').count(),0);
  await page.locator('#page-evidence .page-evidence-toggle button').click();
  await page.locator('#page-evidence img').waitFor();
  assert(await page.locator('#page-evidence img').evaluate(img=>img.complete && img.naturalWidth===900));
  await page.screenshot({path:path.join(run,'page-evidence.png')});
  await page.locator('#page-dialog [data-close]').click();
  await page.getByRole('button',{name:'补录遗漏记录',exact:true}).click();
  await page.locator('#manual-page').fill('1');
  await page.locator('[name="transaction_at"]').fill('2026-09-05');
  await page.locator('[name="amount"]').fill('15');
  await page.locator('[name="direction"]').selectOption('out');
  await page.locator('[name="currency"]').fill('CNY');
  await page.locator('#record-note').fill('对照合成原页补录唯一一条交易');
  await page.locator('#save-record').click();
  await page.locator('#detail-dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'查看原页 / 核对笔数',exact:true}).click();
  await page.locator('#observed-count').fill('1');await page.locator('#page-note').fill('原页共一笔，与补录后的记录一致');
  await page.getByRole('button',{name:'保存页核验',exact:true}).click();
  await page.locator('#page-dialog').waitFor({state:'hidden'});
  await page.getByText('本批次没有待处理的读取问题。',{exact:false}).waitFor();
  await page.locator('[data-page="overview"]').click();
  assert.equal(await page.locator('#kpi-eligible').innerText(),'1');
  assert.equal(await page.locator('#kpi-pages').innerText(),'0');
  results.push('零记录失败页面可见、鉴权原图可看、手工补录和页笔数核验闭环');
  // The intentional stale write produces an expected HTTP 409 console entry.
  const unexpected=errors.filter(e=>!e.includes('409 (Conflict)'));
  assert.equal(unexpected.length,0,unexpected.join('\n'));
  fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({results,browser:'Edge headless',unexpectedErrors:unexpected},null,2));
  console.log(JSON.stringify({run,results,unexpectedErrors:unexpected},null,2));
})().catch(async e=>{if(testPage){await testPage.screenshot({path:path.join(run,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(run,'failure.txt'),await testPage.locator('body').innerText().catch(()=>''));}console.error(e);console.error('Artifacts: '+run);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await stop();});
